# This file was generated by GoReleaser. DO NOT EDIT.
cask "warren" do
  version "1.4.0"

  on_macos do
    on_arm do
      sha256 "69e5bf84b722352b421909fb68deeeb5489b070de09954c611360189a61cf032"
      url "https://github.com/treyperrone/warren/releases/download/v#{version}/warren_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "524cc03dc2fbb46d4a1fa3554f9f6f2e790881905fd10c4af68b58e6424bb8ca"
      url "https://github.com/treyperrone/warren/releases/download/v#{version}/warren_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "566f4228d07646417b882bfe9388ac131858ccf42cb993861de39c8dacee4a87"
      url "https://github.com/treyperrone/warren/releases/download/v#{version}/warren_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9a70a78aaa81092156e0053db52b0beba8e192d191ce879213666525808abbb0"
      url "https://github.com/treyperrone/warren/releases/download/v#{version}/warren_#{version}_linux_amd64.tar.gz"
    end
  end

  name "warren"
  desc "Browse AWS accounts and connect to EC2 instances over SSM"
  homepage "https://github.com/treyperrone/warren"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warren"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/warren"]
    end
  end

  # No zap stanza required
end
