# This file was generated by GoReleaser. DO NOT EDIT.
cask "warren" do
  version "1.4.1"

  on_macos do
    on_arm do
      sha256 "bf66afafa3fffe699069d36a8be6c5ceb831763dd2eb76c4675ec5832d914b3c"
      url "https://github.com/treyperrone/warren/releases/download/v#{version}/warren_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6ec2b528a24f37ce172e239876ca37ef63a37ae3b6943cdadd94600c4d9b9a83"
      url "https://github.com/treyperrone/warren/releases/download/v#{version}/warren_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0dec57906acb3531339f645ebd7f68b091663985c2b7e71599561b8b67a21104"
      url "https://github.com/treyperrone/warren/releases/download/v#{version}/warren_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6aac7f592bf17510725112d829741361beff3ae5333cc42f3807b48e9bc436a1"
      url "https://github.com/treyperrone/warren/releases/download/v#{version}/warren_#{version}_linux_amd64.tar.gz"
    end
  end

  name "warren"
  desc "Browse AWS accounts and connect to EC2 instances over SSM"
  homepage "https://github.com/treyperrone/warren"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warren"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/warren"]
    end
  end

  # No zap stanza required
end
