# This file was generated by GoReleaser. DO NOT EDIT.
cask "warren" do
  version "1.5.0"

  on_macos do
    on_arm do
      sha256 "795080cf013ce739d083d4257bddcd1f489dc0527a8f4a70223b7441da5ff253"
      url "https://github.com/treyperrone/warren/releases/download/v#{version}/warren_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cb16f0b0bbfb5e084350e50e741332aac9e1577a91afe3b9a3d1fbe0231afb39"
      url "https://github.com/treyperrone/warren/releases/download/v#{version}/warren_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "16a9e070c512e6b7e33083e52a54dc6ac7fcffe96d42ad0d7ef75a5ebc898ada"
      url "https://github.com/treyperrone/warren/releases/download/v#{version}/warren_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dab981ea2a7692329865789347fa8e7afcac7af008f6c58d65ab91829320d82c"
      url "https://github.com/treyperrone/warren/releases/download/v#{version}/warren_#{version}_linux_amd64.tar.gz"
    end
  end

  name "warren"
  desc "Browse AWS accounts and connect to EC2 instances over SSM"
  homepage "https://github.com/treyperrone/warren"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warren"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/warren"]
    end
  end

  # No zap stanza required
end
